export type QuestionType = 'single' | 'multi' | 'scale' | 'text' | 'conditional-email'

export interface SurveyQuestion {
  id: string
  section: number
  sectionName: string
  question: string
  type: QuestionType
  options?: string[]
  placeholder?: string
  scaleMin?: number
  scaleMax?: number
  scaleMinLabel?: string
  scaleMaxLabel?: string
  conditionalTriggers?: string[] // options that reveal the email field
  required?: boolean
}

export const surveyQuestions: SurveyQuestion[] = [
  // ─── SECTION 1: About You ───────────────────────────────────
  {
    id: 'startup_stage',
    section: 1,
    sectionName: 'About You',
    question: 'What stage is your startup at right now?',
    type: 'single',
    required: true,
    options: [
      'Idea / Pre-product',
      'Building (no users yet)',
      'Early users (pre-revenue)',
      'Revenue (under $10K MRR)',
      'Growing ($10K–$50K MRR)',
      'Scaling ($50K+ MRR)',
    ],
  },
  {
    id: 'location',
    section: 1,
    sectionName: 'About You',
    question: 'Where is your startup based?',
    type: 'single',
    required: true,
    options: [
      'Nigeria',
      'Kenya',
      'Ghana',
      'South Africa',
      'Other African country',
      'United Kingdom',
      'United States',
      'Europe (other)',
      'Other',
    ],
  },
  {
    id: 'sector',
    section: 1,
    sectionName: 'About You',
    question: 'What sector are you building in?',
    type: 'single',
    required: true,
    options: [
      'Fintech / Payments',
      'SaaS / B2B Software',
      'HealthTech',
      'EdTech',
      'E-commerce / Marketplace',
      'Logistics / Mobility',
      'AgriTech',
      'Consumer App',
      'CleanTech / Climate',
      'Other',
    ],
  },
  {
    id: 'time_building',
    section: 1,
    sectionName: 'About You',
    question: 'How long have you been building your current startup?',
    type: 'single',
    required: true,
    options: [
      'Less than 6 months',
      '6–12 months',
      '1–2 years',
      '2–3 years',
      'More than 3 years',
    ],
  },
  {
    id: 'funding_status',
    section: 1,
    sectionName: 'About You',
    question: 'Have you raised external funding?',
    type: 'single',
    required: true,
    options: [
      'No, bootstrapped',
      'Yes — friends & family / angels',
      'Yes — pre-seed VC',
      'Yes — seed VC',
      'Yes — Series A or beyond',
    ],
  },

  // ─── SECTION 2: How You Currently Measure PMF ───────────────
  {
    id: 'pmf_confidence',
    section: 2,
    sectionName: 'How You Measure PMF',
    question: 'On a scale of 1–10, how confident are you in your current ability to measure product-market fit?',
    type: 'scale',
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: 'Not confident at all',
    scaleMaxLabel: 'Extremely confident',
    required: true,
  },
  {
    id: 'pmf_methods',
    section: 2,
    sectionName: 'How You Measure PMF',
    question: 'How do you currently measure product-market fit? Select all that apply.',
    type: 'multi',
    required: true,
    options: [
      'Revenue / MRR growth',
      'User growth / MAU',
      'Retention rate / churn',
      'Net Promoter Score (NPS)',
      'Sean Ellis "very disappointed" survey',
      'Engagement metrics (DAU/MAU ratio)',
      'Qualitative user interviews',
      'Investor feedback',
      'Gut feel / intuition',
      'I don\'t measure it formally',
      'Other',
    ],
  },
  {
    id: 'tracks_retention_cohorts',
    section: 2,
    sectionName: 'How You Measure PMF',
    question: 'Do you track retention cohorts for your product?',
    type: 'single',
    required: true,
    options: [
      'Yes, weekly cohorts',
      'Yes, monthly cohorts',
      'Occasionally, but not consistently',
      'No — I know I should but haven\'t set it up',
      'No — I don\'t think it applies to my product',
      'I\'m not sure what retention cohorts are',
    ],
  },
  {
    id: 'knows_d30_retention',
    section: 2,
    sectionName: 'How You Measure PMF',
    question: 'Do you know your D30 retention rate off the top of your head right now?',
    type: 'single',
    required: true,
    options: [
      'Yes, exactly',
      'Approximately — within 5%',
      'Roughly — within 20%',
      'No, I\'d have to look it up',
      'No, I don\'t track this',
      'This metric doesn\'t apply to my product',
    ],
  },
  {
    id: 'pmf_data_locations',
    section: 2,
    sectionName: 'How You Measure PMF',
    question: 'Where does your PMF-related data currently live?',
    type: 'multi',
    required: true,
    options: [
      'Stripe / payment platform',
      'Mixpanel / Amplitude / product analytics',
      'Google Analytics',
      'Intercom / customer support tool',
      'HubSpot / CRM',
      'Spreadsheets / Excel / Google Sheets',
      'Notion / internal docs',
      'In my head',
      'It\'s scattered — no single place',
      'I don\'t have a structured data setup',
    ],
  },
  {
    id: 'time_to_pmf_proof',
    section: 2,
    sectionName: 'How You Measure PMF',
    question: 'How long would it take you to pull together a clear PMF picture right now if an investor asked?',
    type: 'single',
    required: true,
    options: [
      'Less than 10 minutes — I have it ready',
      '30 minutes to an hour',
      'A few hours',
      'A full day or more',
      'I wouldn\'t know where to start',
      'I don\'t think I could produce one right now',
    ],
  },
  {
    id: 'sean_ellis_usage',
    section: 2,
    sectionName: 'How You Measure PMF',
    question: 'Have you ever used the Sean Ellis test (asking users: \'How disappointed would you be if this product disappeared?\')?',
    type: 'single',
    required: true,
    options: [
      'Yes — and 40%+ said "very disappointed" (strong PMF signal)',
      'Yes — and fewer than 40% said "very disappointed"',
      'Yes — but I don\'t know what the benchmark means',
      'No — I\'ve heard of it but never run it',
      'No — I\'ve never heard of it',
    ],
  },

  // ─── SECTION 3: The Investor Moment ─────────────────────────
  {
    id: 'investor_pmf_question',
    section: 3,
    sectionName: 'The Investor Moment',
    question: 'Has an investor ever asked you to prove your product-market fit?',
    type: 'single',
    required: true,
    options: [
      'Yes — and I had a strong, data-backed answer',
      'Yes — and I had a partial answer but wasn\'t fully confident',
      'Yes — and I struggled to answer clearly',
      'Yes — and I couldn\'t answer satisfactorily',
      'Not yet — but I\'m preparing for this conversation',
      'I haven\'t had investor conversations yet',
    ],
  },
  {
    id: 'investor_show_data',
    section: 3,
    sectionName: 'The Investor Moment',
    question: 'If an investor asked "show me your PMF data" right now, what would you show them?',
    type: 'text',
    placeholder: 'Be honest — what would you actually pull up?',
    required: false,
  },
  {
    id: 'unclear_pmf_cost',
    section: 3,
    sectionName: 'The Investor Moment',
    question: 'Has unclear PMF ever cost you a funding conversation?',
    type: 'single',
    required: true,
    options: [
      'Yes — I\'m certain it has',
      'Possibly — I suspected it but wasn\'t told directly',
      'No — not yet',
      'I haven\'t pursued funding',
    ],
  },
  {
    id: 'runway_wasted',
    section: 3,
    sectionName: 'The Investor Moment',
    question: 'How much runway have you spent building features before realising you weren\'t solving the right problem?',
    type: 'single',
    required: true,
    options: [
      'None — I\'ve validated everything before building',
      '1–3 months of runway',
      '3–6 months of runway',
      '6–12 months of runway',
      'More than a year of runway',
      'I\'m still not sure if I\'m solving the right problem',
    ],
  },

  // ─── SECTION 4: Your Tools & Data Stack ─────────────────────
  {
    id: 'tools_used',
    section: 4,
    sectionName: 'Your Tools & Data Stack',
    question: 'Which tools do you currently use? Select all that apply.',
    type: 'multi',
    required: true,
    options: [
      'Stripe',
      'Paystack',
      'Flutterwave',
      'Mixpanel',
      'Amplitude',
      'Google Analytics (GA4)',
      'Intercom',
      'HubSpot',
      'Salesforce',
      'Segment',
      'ChartMogul / Baremetrics',
      'Hotjar / FullStory',
      'PostHog',
      'Typeform / SurveyMonkey',
      'Notion',
      'Slack',
      'None of the above',
      'Other',
    ],
  },
  {
    id: 'has_unified_dashboard',
    section: 4,
    sectionName: 'Your Tools & Data Stack',
    question: 'Do you currently have a single dashboard that shows you all your key startup metrics in one place?',
    type: 'single',
    required: true,
    options: [
      'Yes — it works well',
      'Yes — but it\'s incomplete or hard to maintain',
      'No — but I\'m building one',
      'No — and this is a pain point for me',
      'No — I use separate tools for each metric',
    ],
  },
  {
    id: 'metrics_known_offhand',
    section: 4,
    sectionName: 'Your Tools & Data Stack',
    question: 'Which of these metrics can you name right now without looking anything up?',
    type: 'multi',
    required: true,
    options: [
      'Monthly Recurring Revenue (MRR)',
      'Month-on-month MRR growth rate',
      'D30 retention rate',
      'Churn rate',
      'Customer Acquisition Cost (CAC)',
      'Lifetime Value (LTV)',
      'NPS score',
      'DAU/MAU ratio',
      'Organic referral rate',
      'None of these off the top of my head',
    ],
  },

  // ─── SECTION 5: The Solution Test ───────────────────────────
  {
    id: 'pmf_score_usefulness',
    section: 5,
    sectionName: 'The Solution Test',
    question: 'How useful would a single PMF Score™ be to you — a number from 1–100 built from your existing tools that tells you exactly where you stand on product-market fit?',
    type: 'scale',
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: 'Not useful at all',
    scaleMaxLabel: 'Extremely useful',
    required: true,
  },
  {
    id: 'pmf_score_use_cases',
    section: 5,
    sectionName: 'The Solution Test',
    question: 'What would you use a PMF Score™ for? Select all that apply.',
    type: 'multi',
    required: true,
    options: [
      'Preparing for investor conversations',
      'Deciding whether to pivot or stay the course',
      'Aligning my team around a shared goal',
      'Tracking progress week-on-week',
      'Benchmarking against other startups in my sector',
      'Communicating traction to advisors or board',
      'I\'m not sure I\'d use it',
    ],
  },
  {
    id: 'biggest_pmf_frustration',
    section: 5,
    sectionName: 'The Solution Test',
    question: 'What is your biggest frustration with how you currently measure PMF?',
    type: 'text',
    placeholder: 'Don\'t hold back — we want the honest answer.',
    required: false,
  },
  {
    id: 'pricing_tier',
    section: 5,
    sectionName: 'The Solution Test',
    question: 'If VeloDesk existed today, which plan would you most likely consider?',
    type: 'single',
    required: true,
    options: [
      'Free tier (basic PMF Score™, limited integrations)',
      '$29/month (full PMF Score™, all integrations, monthly report)',
      '$79/month (everything + investor-ready export, AI recommendations)',
      '$199/month (team plan, unlimited integrations, dedicated PMF diagnostic)',
      'I wouldn\'t pay for this',
      'I\'d need to know more before deciding',
    ],
  },
  {
    id: 'would_recommend',
    section: 5,
    sectionName: 'The Solution Test',
    question: 'Would you recommend a PMF validation tool to other founders in your network?',
    type: 'single',
    required: true,
    options: [
      'Yes — immediately, if it worked',
      'Yes — after I\'d tested it myself',
      'Maybe — depends on the price',
      'Unlikely',
      'No',
    ],
  },
  {
    id: 'trust_requirements',
    section: 5,
    sectionName: 'The Solution Test',
    question: 'What would need to be true for you to trust a PMF Score™?',
    type: 'text',
    placeholder: 'What would make you confident the score was real and accurate?',
    required: false,
  },
  {
    id: 'follow_up_consent',
    section: 5,
    sectionName: 'The Solution Test',
    question: 'May we follow up with you about the research findings and early access to VeloDesk?',
    type: 'conditional-email',
    required: true,
    options: [
      'Yes — I\'d like the research findings and early access info',
      'Yes — but only for the research findings (no product emails)',
      'No — keep my responses anonymous',
    ],
    conditionalTriggers: [
      'Yes — I\'d like the research findings and early access info',
      'Yes — but only for the research findings (no product emails)',
    ],
  },
]

export const sectionNames = [
  'About You',
  'How You Measure PMF',
  'The Investor Moment',
  'Your Tools & Data Stack',
  'The Solution Test',
]

export const totalQuestions = surveyQuestions.length
export const totalSections = sectionNames.length
